language: cpp

os:
  - osx

# safelist
branches:
  only:
    - deployment

before_install:
  - brew update

install:
  - brew install qt5
  - brew link --force qt5

script:
  # Run qmake and make
  - qmake -config release
  - make
  - ls -alh
  - ls -alh build
  - ls -alh build/release
  # mac specific deployment
  - /usr/local/opt/qt5/bin/macdeployqt build/release/YUView.app -always-overwrite -verbose=2
  - otool -L build/release/YUView.app/Contents/MacOs/YUView
  - cp libde265/libde265-internals.dylib build/release/YUView.app/Contents/MacOS/.
  - zip -r YUView-MacOs.zip build/release/YUView.app
  - git config --global user.email "blaeser@ient.rwth-aachen.de"
  - git config --global user.name "Travis CI"
  - git clone -b deploy_mac --single-branch https://${GH_TOKEN}@github.com/IENT/YUViewReleases.git --depth 1
  - cd YUViewReleases
  - git rm --cached YUView-MacOs.zip
  - git add . *.zip
  - cp ../YUView-MacOs.zip .
  - git commit --message "Travis build ${TRAVIS_BUILD_NUMBER}, ${TRAVIS_BUILD_ID} based on ${TRAVIS_COMMIT}"
  - git push

after_success:
  # empty

before_deploy:
  # empty
deploy:
  # We need the compiled files
  # skip_cleanup: true
  # Here we can deploy. Or it could be done in the before_deploy or after_success steps.
