language: cpp

os:
  - osx

branches:
  only:
    - deployment

before_install:
  - brew update

install:
  - brew install qt5
  - brew link --force qt5

script:
  # Run qmake and make
  - qmake -config release
  - make
  - ls -alh
  - ls -alh build
  - ls -alh build/release
  # mac specific deployment
  - /usr/local/opt/qt5/bin/macdeployqt build/release/YUView.app -always-overwrite -verbose=2
  # check what YUView is linking against
  - otool -L build/release/YUView.app/Contents/MacOs/YUView
  # copy the libde265 library
  - cp libde265/libde265-internals.dylib build/release/YUView.app/Contents/MacOS/.
  # prepare zip package
  - cd build/release
  - zip -r ../../YUView-MacOs.zip YUView.app
  - cd ../..
  # deploy the zip file to the YUViewReleases repo
  - git config --global user.email "blaeser@ient.rwth-aachen.de"
  - git config --global user.name "Travis CI"
  - git clone -b master --single-branch https://${GH_TOKEN}@github.com/IENT/YUViewReleases.git --depth 1
  - cd YUViewReleases
  # delete old file from cache just in case
  - git rm --ignore-unmatch mac/*
  # copy the new file
  - mkdir -p mac
  - cp -f ../YUView-MacOs.zip mac/.
  - git add mac/*
  # unlike Appveyor, TravisCI has no problems with environment variables..
  - git commit --allow-empty --message "Travis build ${TRAVIS_BUILD_NUMBER}, ${TRAVIS_BUILD_ID} based on ${TRAVIS_COMMIT}"
  - git push

after_success:
  # not needed?

before_deploy:
  # not needed?
deploy:
  # we could also put the package somewhere else

