image: Visual Studio 2015
configuration: Release
platform:
  - x64
clone_folder: C:\projects\YUView

branches:
  only:
    - deployment
  
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - set QTDIR=C:\Qt\5.11.1\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - cd C:\projects\YUView
  - cd

build_script:
  - qmake
  - where nmake
  - nmake
  
after_build:
  - cd
  - mkdir deploy
  - windeployqt --release --dir C:\projects\YUView\deploy  ../build/release/YUView.exe
  - copy C:\OpenSSL-Win64\bin\*.dll deploy\.
  - mkdir libde265
  - copy ..\libde265\libde265-internals.dll libde265
  - 7z a YUView-VS-MT.zip deploy
  - cd C:\projects\YUView
  - cd
  
artifacts:
  - path: YUView-VS-MT.zip
    name: YUView
