image: Visual Studio 2015
configuration: Release
platform:
  - x64
clone_folder: C:\projects\YUView

branches:
  except:
    - gh-pages
  
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - cd
  - cd C:\projects
  - mkdir Qt
  - cd Qt
  - git clone https://github.com/ChristianFeldmann/Qt5.8VS-MT.git .
  - set QTDIR=C:\projects\Qt\5.8-release\qtbase
  - set PATH=%PATH%;%QTDIR%\bin
  - cd C:\projects\YUView
  - cd

build_script:
  - qmake
  - where nmake
  - nmake

after_build:
  # Create a directory where we collect everything
  - cd
  - mkdir deploy
  - cd deploy
  # Copy the executable
  - copy ..\release\YUView.exe .
  # Copy the openSSL files
  - copy C:\projects\Qt\openSSL\*.dll .
  # Copy all the Qt dependencies (this is what windeployqt should do - does not work)
  - copy C:\projects\Qt\5.8-release\qtbase\lib\Qt5Core.dll .
  - copy C:\projects\Qt\5.8-release\qtbase\lib\Qt5Gui.dll .
  - copy C:\projects\Qt\5.8-release\qtbase\lib\Qt5Network.dll .
  - copy C:\projects\Qt\5.8-release\qtbase\lib\Qt5Widgets.dll .
  - copy C:\projects\Qt\5.8-release\qtbase\lib\Qt5Xml.dll .
  # And subdirs
  - mkdir bearer
  - copy C:\projects\Qt\5.8-release\qtbase\plugins\bearer\*.dll bearer
  - mkdir imageformats
  - copy C:\projects\Qt\5.8-release\qtbase\plugins\imageformats\*.dll imageformats
  - mkdir libde265
  - copy ..\libde265\libde265-internals.dll libde265
  - mkdir platforms
  - copy C:\projects\Qt\5.8-release\qtbase\plugins\platforms\qwindows.dll platforms
  # Done. Now pack everything into a zip file
  - 7z a ..\YUView-VS-MT.zip .
  - cd C:\projects\YUView
  - cd
  
artifacts:
  - path: YUView-VS-MT.zip
    name: YUView
  
  