image: Visual Studio 2015
configuration: Release
platform:
  - x64
clone_folder: C:\projects\YUView
environment:
  access_token:
    secure: OrnQm0bZgvYKk66eRxDm/83jxiWBWrCoXigQd9u3v2lrRPXFR5x+oaFQVlc05Ize

branches:
  only:
    - deployment
  
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - set QTDIR=C:\Qt\5.11.1\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - cd C:\projects\YUView
  - cd

build_script:
  - C:\msys64\usr\bin\sed.exe -i -- "s/#define UPDATE_FEATURE_ENABLE 0/#define UPDATE_FEATURE_ENABLE 1/g" source/typedef.h
  - qmake
  - where nmake
  - nmake
  
after_build:
  - cd
  - mkdir deploy
  - cd deploy
  - windeployqt --release --dir C:\projects\YUView\deploy  ..\build\release\YUView.exe
  - copy ..\build\release\YUView.exe .
  - copy C:\OpenSSL-Win64\bin\ssleay32.dll .
  - mkdir libde265
  - copy ..\libde265\libde265-internals.dll libde265
  - copy ..\libde265\LICENCE.TXT libde265
  - copy ..\LICENSE.GPL3 .
  - cd C:\projects\YUView
  - python deployment\versioning.py -d deploy -o deploy\versioninfo.txt
  - 7z a YUView-Win.zip deploy
  - makensis deployment\deploy.nsi
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "blaeser@ient.rwth-aachen.de"
  - git config --global user.name "Appveyor"
  - git clone -b deploy_win --single-branch https://github.com/IENT/YUViewReleases.git --depth 1
  - cd YUViewReleases
  - cp ../YUView-Win.zip .
  - cp ../SetupYUView.exe .
  - git add . *.zip
  - git add . *.exe
  - git commit --message "Apveyor build"
  - git push --quiet
  
artifacts:
  - path: YUView-Win.zip
    name: YUView Zip Folder
    type: zip
    
  - path: SetupYUView.exe
    name: YUView Installer
