image: Visual Studio 2015
configuration: Release
platform:
  - x64
clone_folder: C:\projects\YUView
environment:
  access_token:
    secure: OrnQm0bZgvYKk66eRxDm/83jxiWBWrCoXigQd9u3v2lrRPXFR5x+oaFQVlc05Ize

branches:
  only:
    - deployment
  
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - set QTDIR=C:\Qt\5.11.1\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - cd C:\projects\YUView
  - cd

build_script:
  - qmake
  - where nmake
  - nmake
  
after_build:
  - cd
  - mkdir deploy
  - cd deploy
  - windeployqt --release --dir C:\projects\YUView\deploy  ..\build\release\YUView.exe
  - copy ..\build\release\YUView.exe .
  - copy C:\OpenSSL-Win64\bin\ssleay32.dll .
  - mkdir libde265
  - copy ..\libde265\libde265-internals.dll libde265
  - copy ..\libde265\LICENCE.TXT libde265
  - copy ..\LICENSE.GPL3 deploy
  - cd C:\projects\YUView
  - python deployment\versioning.py -d deploy -o deploy\versioninfo.txt
  - 7z a YUView.zip deploy
# - makensis deployment\deploy.nsi
  
artifacts:
  - path: YUView.zip
    name: YUView
