name: yuview
version: git
summary: YUView
description: YUView - The free cross platform YUV viewer and video analysis tool

grade: stable
confinement: strict
type: app
icon: images/IENT-YUView-64.png
architectures: 
  - build-on: amd64
    run-on: amd64

apps:
  yuview:
    command: desktop-launch ${SNAP}/usr/bin/YUView
    desktop: usr/share/applications/YUView.desktop 
    plugs: [home, network, x11, wayland, desktop, desktop-legacy, opengl, gsettings, removable-media]
    environment: 
        QT_NO_FT_CACHE: 1        
        LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-gnu-linux:$SNAP/lib/x86_64-gnu-linux
        PATH: $SNAP/usr/bin:$SNAP/bin:$PATH

parts:
  yuview:
    plugin: qmake
    source: ./
    project-files: [YUView.pro]
    qt-version: qt5
    build-packages:
      - qtbase5-dev
      - libqt5gui5
      - libqt5opengl5
      - libqt5opengl5-dev
      - libqt5xml5
      - libqt5concurrent5
      - libqt5network5
      - libqt5core5a
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - qtbase5-dev
      - libqt5opengl5
      - libqt5widgets5
    after: [desktop-qt5, indicator-qt5]
  libde265:
    source-type:    git
    source-branch: internal
    plugin:         cmake
    configflags: ["-DONLY_LIB=ON"]
    source: https://github.com/nolyn/libde265.git
